package:
    name: "libgpuarray"
    version: "0.6.0"

source:
    git_url: https://github.com/Theano/libgpuarray.git
    git_rev: master  # TODO: this is for testing. Change to a version tag when done.

build:
    number: 0
    script_env: MPI_LIBRARY

requirements:
    build:
        - cmake
        - gcc               # [linux]
        - llvm              # [osx]
        - vs2015_runtime    # [win]

    run:
        - vs2015_runtime    # [win]

about:
    home: https://github.com/Theano/libgpuarray
    license: MIT
    license_file: LICENSE
    summary: "Library to manipulate tensors on the GPU."

extra:
    maintainers:
