# - Try to find clBLAS
#  Once done this will define
#
#  CLBLAS_FOUND - system has clBLAS
#  CLBLAS_INCLUDE_DIRS - location of clBLAS.h
#  CLBLAS_LIBRARIES - location of libclBLAS
#  

FIND_PACKAGE( PackageHandleStandardArgs )

FIND_PATH(CLBLAS_INCLUDE_DIRS clBLAS.h)
FIND_LIBRARY(CLBLAS_LIBRARIES clBLAS ENV LD_LIBRARY_PATH)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(clBLAS DEFAULT_MSG CLBLAS_LIBRARIES CLBLAS_INCLUDE_DIRS)

MARK_AS_ADVANCED(CLBLAS_INCLUDE_DIRS CLBLAS_LIBRARIES)