version: '0.7.0.{build}'

pull_requests:
  do_not_increment_build_number: true

init:
  - git config --global core.autocrlf input
  - cmd: cmake --version
  - cmd: msbuild /version

platform:
  - x64

clone_folder: C:\projects\libgpuarray

configuration:
  - Release
  - Debug

environment:
  matrix:
    - PYTHON: "C:\\Miniconda-x64"
      CONDA_PY: 27
#      VS_PATH: "C:\\Users\\appveyor\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0"
    - PYTHON: "C:\\Python36-x64"
      CONDA_PY: 36
#      VS_PATH: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC"

install:
  # This breaks conda-build because of git
  - cmd: rmdir C:\cygwin /s /q
  - cmd: call %CONDA_LOC%\Scripts\activate.bat
  - cmd: set PYTHONUNBUFFERED=1
  - cmd: conda install -n root --yes conda conda-env conda-build anaconda-client

build: script

build_script:
  - conda build conda --quiet

#deploy_script:
