
/* This file is generated by gen_blas.py in the root of the distribution */
#ifndef COMPYTE_BLAS_H
#define COMPYTE_BLAS_H

#include <compyte/buffer_blas.h>
#include <compyte/array.h>

COMPYTE_PUBLIC int GpuArray_rgemv(const cb_transpose transA, const double alpha, GpuArray *A, GpuArray *X, const double beta, GpuArray *Y,
                                        int nocopy);
#define GpuArray_sgemv GpuArray_rgemv
#define GpuArray_dgemv GpuArray_rgemv
#endif
