
/* This file is generated by gen_blas.py in the root of the distribution */
#ifndef COMPYTE_BLAS_H
#define COMPYTE_BLAS_H

#include <compyte/buffer_blas.h>
#include <compyte/array.h>

COMPYTE_PUBLIC int GpuArray_rgemv(cb_transpose transA, double alpha, GpuArray *A, GpuArray *X, double beta, GpuArray *Y,
                                        int nocopy);
#define GpuArray_sgemv GpuArray_rgemv
#define GpuArray_dgemv GpuArray_rgemv
COMPYTE_PUBLIC int GpuArray_rgemm(cb_transpose transA, cb_transpose transB, double alpha, GpuArray *A, GpuArray *B, double beta, GpuArray *C,
                                        int nocopy);
#define GpuArray_sgemm GpuArray_rgemm
#define GpuArray_dgemm GpuArray_rgemm
#endif
